name: test
on: push
jobs:
  #my_first_job:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: print some stuff
  #      run: printenv
  #checkout:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  my_container_job:
    runs-on: ubuntu-latest
    container: gittools/gitversion:5.2.4-linux-centos-7-netcoreapp2.1
    steps:
      - name: install git
        run: yum -y install  https://centos7.iuscommunity.org/ius-release.rpm && yum -y install  git2u-all
      - uses: actions/checkout@v2
      - name: git status
        run: git status
      - name: print it
        run: realpath . && ls .
      - name: print it
        run: /tools/dotnet-gitversion
      #- name: do something to the file system
      #  run: touch wakka123.txt && ls .
  #my_third_job:
  #  needs: [my_container_job]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: print it
  #      run: ls .
  #    - name: set env
  #      run: echo ::set-env name=action_state::yellow
  #    - name: print some stuff 2
  #      run: printenv